version: '3.8'

services:
  # MongoDB Database
  mongodb: 
    image: mongo:6.0
    container_name: inventory-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: grocery_inventory
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - inventory-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/grocery_inventory?authSource=admin
      JWT_SECRET: your_jwt_secret_key_here
      JWT_EXPIRE: 7d
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: your_email@gmail.com
      EMAIL_PASS: your_app_password
      VENDOR_EMAIL: vendor@example.com
      LOW_STOCK_THRESHOLD: 10
    depends_on:
      - mongodb
    networks:
      - inventory-network
    volumes:
      - ./backend/.env:/app/.env:ro

  # Frontend (Development)
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: inventory-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - inventory-network
    profiles:
      - dev

volumes:
  mongodb_data:

networks:
  inventory-network:
    driver: bridge
