@echo off
echo Restarting frontend with new proxy configuration...

echo Stopping any running frontend processes...
taskkill /F /IM node.exe 2>nul

echo Waiting 2 seconds...
timeout /t 2 /nobreak > nul

echo Starting frontend...
cd frontend
npm start
